
[project]
name = "civil_calc"
version = "0.1.0"
dependencies = [
    "pandas",
    "openpyxl"
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
